In [1]:
#Loading in the pandas library
import pandas as pd

In [2]:
#Open both of our raw data files in pandas and converting them into panda dataframes
KinaseSubstrateDF = pd.read_excel('Kinase_Substrate_Dataset_UNEDITED.xlsm')
PhosphorylationSiteDF = pd.read_excel('Phosphorylation_site_dataset_UNEDITED.xlsm')

In [3]:
#Checking that both dataframes loaded in correctly
KinaseSubstrateDF.head()

,GENE,KINASE,KIN_ACC_ID,KIN_ORGANISM,SUBSTRATE,SUB_GENE_ID,SUB_ACC_ID,SUB_GENE,SUB_ORGANISM,SUB_MOD_RSD,SITE_GRP_ID,SITE_+/-7_AA,DOMAIN,IN_VIVO_RXN,IN_VITRO_RXN,CST_CAT#
0,Pak2,PAK2,Q64303,rat,MEK1,170851.0,Q01986,Map2k1,rat,S298,448284,RtPGRPLsSYGMDSR,Pkinase,,X,9128; 98195
1,Pak2,PAK2,Q64303,rat,PRKD1,85421.0,Q9WTQ1,Prkd1,rat,S203,449896,GVRRRRLsNVsLTGL,NaN,X,,NaN
2,Pak2,PAK2,Q64303,rat,prolactin,5617.0,P01236,PRL,human,S207,451732,LHCLRRDsHKIDNYL,Hormone_1,,X,NaN
3,Pak2,PAK2,Q64303,rat,prolactin,24683.0,P01237,Prl,rat,S206,451732,IRCLRRDsHKVDNYL,Hormone_1,,X,NaN
4,EIF2AK1,HRI,Q9BQI3,human,eIF2-alpha,54318.0,P68101,Eif2s1,rat,S52,447635,MILLSELsRRRIRSI,S1,,X,3597; 9721; 3398; 5199

In [4]:
PhosphorylationSiteDF.head()

,GENE,PROTEIN,ACC_ID,HU_CHR_LOC,MOD_RSD,SITE_GRP_ID,ORGANISM,MW_kD,DOMAIN,SITE_+/-7_AA,LT_LIT,MS_LIT,MS_CST,CST_CAT#
0,1110035H17Rik,1110035H17Rik,Q9CTA4,7|7,S10-p,7231581,mouse,24.31,NaN,RPPPGSRstVAQSPP,NaN,1.0,NaN,NaN
1,1110035H17Rik,1110035H17Rik,Q9CTA4,7|7,T11-p,7231583,mouse,24.31,NaN,PPPGSRstVAQSPPQ,NaN,1.0,NaN,NaN
2,YWHAB,14-3-3 beta,P31946,20q13.12,T2-p,15718712,human,28.08,NaN,______MtMDksELV,NaN,3.0,1.0,NaN
3,Ywhab,14-3-3 beta,Q9CQV8,2|2 H3,T2-p,15718712,mouse,28.09,NaN,______MtMDksELV,NaN,2.0,NaN,NaN
4,YWHAB,14-3-3 beta,P31946,20q13.12,S6-p,15718709,human,28.08,NaN,__MtMDksELVQkAk,NaN,8.0,NaN,NaN

In [10]:
###Filtering and Cleaning for Kinase_Substrate dataset###

#Filter data in the data frame to only include data where the Kinase Organism and Substrate Organism are both Human
HUMANfilteredKSDF = KinaseSubstrateDF[(KinaseSubstrateDF.KIN_ORGANISM=='human') & (KinaseSubstrateDF.SUB_ORGANISM=='human')]

#Remove the columns of data in the data frame that we do not need for our database
KSDFColumnsEdit = HUMANfilteredKSDF.drop(['KIN_ORGANISM', 'SUB_ORGANISM', 'IN_VIVO_RXN', 'IN_VITRO_RXN', 'CST_CAT#'],axis=1)

#Changing the column title for Neighbouring AAs so that if we want to manipulate it further in Python we can do without syntax errors
KSDFColumnCorrected = KSDFColumnsEdit.rename(columns = {'SITE_+/-7_AA': 'SITE_7_AA'})

In [11]:
###Filtering and Cleaning for Phosphorylation_Dataset dataset###

#Filter data in the data frame to only include data where the Kinase Organism and Substrate Organism are both Human
HUMANfilteredPSDF = PhosphorylationSiteDF[PhosphorylationSiteDF.ORGANISM == 'human']

#As we only need this file for the Genomic Locations no further filtering and cleaning is needed.

In [7]:
#KSDFColumnCorrected.to_csv("Filtered_Kinase_Substrate_Table.csv", index = False)
#HUMANfilteredPSDF.to_csv("Filtered_Phosphorylation_Site_Table.csv", index = False)

In [12]:
KSDFColumnCorrected.head()

,GENE,KINASE,KIN_ACC_ID,SUBSTRATE,SUB_GENE_ID,SUB_ACC_ID,SUB_GENE,SUB_MOD_RSD,SITE_GRP_ID,SITE_7_AA,DOMAIN
6,EIF2AK1,HRI,Q9BQI3,eIF2-alpha,1965.0,P05198,EIF2S1,S52,447635,MILLsELsRRRIRsI,S1
7,EIF2AK1,HRI,Q9BQI3,eIF2-alpha,1965.0,P05198,EIF2S1,S49,450210,IEGMILLsELsRRRI,S1
10,PRKCD,PKCD,Q05655,HDAC5,10014.0,Q9UQL6,HDAC5,S259,447995,FPLRkTAsEPNLKVR,NaN
11,PRKCD,PKCD,Q05655,PTPRA iso2,5786.0,P18433-2,PTPRA,S204,447612,PLLARSPsTNRKYPP,NaN
12,PRKCD,PKCD,Q05655,hnRNP K,3190.0,P61978,HNRNPK,S302,457408,GrGGrGGsrArNLPL,NaN

In [9]:
HUMANfilteredPSDF.head()

,GENE,PROTEIN,ACC_ID,HU_CHR_LOC,MOD_RSD,SITE_GRP_ID,ORGANISM,MW_kD,DOMAIN,SITE_+/-7_AA,LT_LIT,MS_LIT,MS_CST,CST_CAT#
2,YWHAB,14-3-3 beta,P31946,20q13.12,T2-p,15718712,human,28.08,NaN,______MtMDksELV,NaN,3.0,1.0,NaN
4,YWHAB,14-3-3 beta,P31946,20q13.12,S6-p,15718709,human,28.08,NaN,__MtMDksELVQkAk,NaN,8.0,NaN,NaN
6,YWHAB,14-3-3 beta,P31946,20q13.12,Y21-p,3426383,human,28.08,14-3-3,LAEQAERyDDMAAAM,NaN,NaN,4.0,NaN
8,YWHAB,14-3-3 beta,P31946,20q13.12,T32-p,23077803,human,28.08,14-3-3,AAAMkAVtEQGHELs,NaN,NaN,1.0,NaN
9,YWHAB,14-3-3 beta,P31946,20q13.12,S39-p,27442700,human,28.08,14-3-3,tEQGHELsNEERNLL,NaN,4.0,NaN,NaN

In [ ]:
EmptyDict = {}